export const transactions = [
  {
    transaction_name: "Grocery Shopping",
    amount: 150.75,
    status: "successful",
    category: "debit",
    date: "2024-05-20",
    benefactor: "Supermarket",
  },
  {
    transaction_name: "Salary",
    amount: 3000.0,
    status: "successful",
    category: "credit",
    date: "2024-05-01",
    benefactor: "Employer",
  },
  {
    transaction_name: "Electricity Bill",
    amount: 85.5,
    status: "pending",
    category: "debit",
    date: "2024-05-22",
    benefactor: "Utility Company",
  },
  {
    transaction_name: "Online Course",
    amount: 200.0,
    status: "failed",
    category: "debit",
    date: "2024-05-15",
    benefactor: "Education Platform",
  },
  {
    transaction_name: "Freelance Payment",
    amount: 1200.0,
    status: "successful",
    category: "credit",
    date: "2024-05-10",
    benefactor: "Client",
  },
  {
    transaction_name: "Restaurant Dinner",
    amount: 75.25,
    status: "successful",
    category: "debit",
    date: "2024-05-18",
    benefactor: "Restaurant",
  },
  {
    transaction_name: "Subscription Renewal",
    amount: 10.99,
    status: "pending",
    category: "debit",
    date: "2024-05-21",
    benefactor: "Streaming Service",
  },
  {
    transaction_name: "Gym Membership",
    amount: 45.0,
    status: "successful",
    category: "debit",
    date: "2024-05-02",
    benefactor: "Fitness Center",
  },
  {
    transaction_name: "Book Purchase",
    amount: 30.0,
    status: "failed",
    category: "debit",
    date: "2024-05-17",
    benefactor: "Bookstore",
  },
  {
    transaction_name: "Bonus",
    amount: 500.0,
    status: "successful",
    category: "credit",
    date: "2024-05-05",
    benefactor: "Employer",
  },
];
